# Generated by Django 4.1.7 on 2023-03-19 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_uri', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=255)),
                ('min_danceability', models.FloatField(default=0)),
                ('max_danceability', models.FloatField(default=1)),
                ('min_valence', models.FloatField(default=0)),
                ('max_valence', models.FloatField(default=1)),
                ('min_energy', models.FloatField(default=0)),
                ('max_energy', models.FloatField(default=1)),
                ('min_tempo', models.FloatField(default=0)),
                ('max_tempo', models.FloatField(default=1)),
                ('min_duration', models.FloatField(default=0)),
                ('max_duration', models.FloatField(default=1000)),
                ('min_loudness', models.FloatField(default=0)),
                ('max_loudness', models.FloatField(default=1)),
                ('min_speechiness', models.FloatField(default=0)),
                ('max_speechiness', models.FloatField(default=1)),
                ('min_instrumentalness', models.FloatField(default=0)),
                ('max_instrumentalness', models.FloatField(default=1)),
                ('min_liveness', models.FloatField(default=0)),
                ('max_liveness', models.FloatField(default=1)),
                ('min_acousticness', models.FloatField(default=0)),
                ('max_acousticness', models.FloatField(default=1)),
                ('play_to_skip_ratio', models.FloatField(default=1.5)),
                ('followers', models.IntegerField(default=1)),
                ('image', models.CharField(max_length=255, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.account')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('danceability', models.FloatField(default=0)),
                ('valence', models.FloatField(default=0)),
                ('energy', models.FloatField(default=0)),
                ('tempo', models.FloatField(default=0)),
                ('duration_ms', models.FloatField(default=0)),
                ('loudness', models.FloatField(default=0)),
                ('speechiness', models.FloatField(default=0)),
                ('instrumentalness', models.FloatField(default=0)),
                ('liveness', models.FloatField(default=0)),
                ('acousticness', models.FloatField(default=0)),
                ('image', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_uri', models.CharField(max_length=200)),
                ('num_plays', models.IntegerField(default=0)),
                ('num_skips', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.account')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hygo.song')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.account')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hygo.playlist')),
            ],
        ),
    ]
